#ifndef HID_DESCRIPTOR_HELPERS_H
#define HID_DESCRIPTOR_HELPERS_H

// Helper macros for building HID descriptors

#ifndef HID_USAGE_PAGE
  #define HID_USAGE_PAGE(x) 0x05, x
#endif

#ifndef HID_USAGE
  #define HID_USAGE(x) 0x09, x
#endif

#ifndef HID_COLLECTION
  #define HID_COLLECTION(x) 0xA1, x
#endif

#ifndef HID_COLLECTION_END
  #define HID_COLLECTION_END 0xC0
#endif

#ifndef HID_REPORT_SIZE
  #define HID_REPORT_SIZE(x) 0x75, x
#endif

#ifndef HID_REPORT_COUNT
  #define HID_REPORT_COUNT(x) 0x95, x
#endif

#ifndef HID_LOGICAL_MIN
  #define HID_LOGICAL_MIN(x) 0x15, x
#endif

#ifndef HID_LOGICAL_MAX
  #define HID_LOGICAL_MAX(x) 0x25, x
#endif

#ifndef HID_INPUT
  #define HID_INPUT(x) 0x81, x
#endif

#ifndef HID_OUTPUT
  #define HID_OUTPUT(x) 0x91, x
#endif

// Define these as needed for common input and output types:
#ifndef HID_INPUT_ARRAY
  // Data, Array, Absolute (for inputs that are arrays)
  #define HID_INPUT_ARRAY 0x00
#endif

#ifndef HID_INPUT_CONSTANT
  #define HID_INPUT_CONSTANT 0x01
#endif

#ifndef HID_OUTPUT_ARRAY
  #define HID_OUTPUT_ARRAY 0x00
#endif

#ifndef HID_OUTPUT_CONSTANT
  #define HID_OUTPUT_CONSTANT 0x01
#endif

// Standard usage page and usage definitions:
#ifndef HID_USAGE_PAGE_DESKTOP
  #define HID_USAGE_PAGE_DESKTOP 0x01
#endif

#ifndef HID_USAGE_DESKTOP_KEYBOARD
  #define HID_USAGE_DESKTOP_KEYBOARD 0x06
#endif

#ifndef HID_USAGE_PAGE_KEYBOARD
  #define HID_USAGE_PAGE_KEYBOARD 0x07
#endif

#ifndef HID_USAGE_PAGE_LED
  #define HID_USAGE_PAGE_LED 0x08
#endif

#ifndef HID_USAGE_PAGE_CONSUMER
  #define HID_USAGE_PAGE_CONSUMER 0x0C
#endif

#ifndef HID_USAGE_CONSUMER_CONTROL
  #define HID_USAGE_CONSUMER_CONTROL 0x01
#endif

#ifndef HID_USAGE_CONSUMER_SCAN_NEXT_TRACK
  #define HID_USAGE_CONSUMER_SCAN_NEXT_TRACK 0xB5
#endif

#ifndef HID_USAGE_CONSUMER_SCAN_PREV_TRACK
  #define HID_USAGE_CONSUMER_SCAN_PREV_TRACK 0xB6
#endif

#ifndef HID_USAGE_CONSUMER_STOP
  #define HID_USAGE_CONSUMER_STOP 0xB7
#endif

#ifndef HID_USAGE_CONSUMER_PLAY_PAUSE
  #define HID_USAGE_CONSUMER_PLAY_PAUSE 0xB8
#endif

#ifndef HID_USAGE_CONSUMER_MUTE
  #define HID_USAGE_CONSUMER_MUTE 0xCD
#endif

#ifndef HID_USAGE_CONSUMER_VOLUME_UP
  #define HID_USAGE_CONSUMER_VOLUME_UP 0xE2
#endif

#ifndef HID_USAGE_CONSUMER_VOLUME_DOWN
  #define HID_USAGE_CONSUMER_VOLUME_DOWN 0xE9
#endif

#ifndef HID_USAGE_CONSUMER_MENU
  #define HID_USAGE_CONSUMER_MENU 0x40  // Example value, adjust if needed
#endif

#ifndef HID_USAGE_CONSUMER_MENU_PICK
  #define HID_USAGE_CONSUMER_MENU_PICK 0x41  // Example value
#endif

#ifndef HID_USAGE_CONSUMER_MENU_UP
  #define HID_USAGE_CONSUMER_MENU_UP 0x42  // Example value
#endif

#ifndef HID_USAGE_CONSUMER_MENU_DOWN
  #define HID_USAGE_CONSUMER_MENU_DOWN 0x43  // Example value
#endif

#ifndef HID_USAGE_CONSUMER_MENU_LEFT
  #define HID_USAGE_CONSUMER_MENU_LEFT 0x44  // Example value
#endif

#ifndef HID_USAGE_CONSUMER_MENU_RIGHT
  #define HID_USAGE_CONSUMER_MENU_RIGHT 0x45  // Example value
#endif

#ifndef HID_USAGE_CONSUMER_MENU_ESCAPE
  #define HID_USAGE_CONSUMER_MENU_ESCAPE 0x46  // Example value
#endif

// For programmable (extra) buttons, define usage IDs as needed. These example values are placeholders:
#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_1
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_1 0xB0
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_2
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_2 0xB1
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_3
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_3 0xB2
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_4
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_4 0xB3
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_5
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_5 0xB4
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_6
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_6 0xB5
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_7
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_7 0xB6
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_8
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_8 0xB7
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_9
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_9 0xB8
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_10
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_10 0xB9
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_11
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_11 0xBA
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_12
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_12 0xBB
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_13
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_13 0xBC
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_14
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_14 0xBD
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_15
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_15 0xBE
#endif

#ifndef HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_16
  #define HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_16 0xBF
#endif

// HID report descriptor definitions

// Media Control Report Descriptor
#define TUD_HID_REPORT_DESC_MEDIA_CONTROL \
    HID_USAGE_PAGE(HID_USAGE_PAGE_CONSUMER), \
    HID_USAGE(HID_USAGE_CONSUMER_CONTROL), \
    HID_COLLECTION(HID_COLLECTION_APPLICATION), \
        HID_LOGICAL_MIN(0), \
        HID_LOGICAL_MAX(1), \
        HID_REPORT_COUNT(16), \
        HID_REPORT_SIZE(1), \
        HID_USAGE(HID_USAGE_CONSUMER_PLAY_PAUSE), \
        HID_USAGE(HID_USAGE_CONSUMER_SCAN_NEXT_TRACK), \
        HID_USAGE(HID_USAGE_CONSUMER_SCAN_PREV_TRACK), \
        HID_USAGE(HID_USAGE_CONSUMER_STOP), \
        HID_USAGE(HID_USAGE_CONSUMER_VOLUME_UP), \
        HID_USAGE(HID_USAGE_CONSUMER_VOLUME_DOWN), \
        HID_USAGE(HID_USAGE_CONSUMER_MUTE), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU_PICK), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU_UP), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU_DOWN), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU_LEFT), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU_RIGHT), \
        HID_USAGE(HID_USAGE_CONSUMER_MENU_ESCAPE), \
        HID_INPUT(HID_INPUT_ARRAY), \
    HID_COLLECTION_END

// Extra Buttons Report Descriptor
#define TUD_HID_REPORT_DESC_EXTRA_BUTTONS \
    HID_USAGE_PAGE(HID_USAGE_PAGE_CONSUMER), \
    HID_USAGE(HID_USAGE_CONSUMER_CONTROL), \
    HID_COLLECTION(HID_COLLECTION_APPLICATION), \
        HID_LOGICAL_MIN(0), \
        HID_LOGICAL_MAX(255), \
        HID_REPORT_COUNT(16), \
        HID_REPORT_SIZE(8), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_1), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_2), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_3), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_4), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_5), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_6), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_7), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_8), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_9), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_10), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_11), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_12), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_13), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_14), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_15), \
        HID_USAGE(HID_USAGE_CONSUMER_PROGRAMMABLE_BUTTON_16), \
        HID_INPUT(HID_INPUT_ARRAY), \
    HID_COLLECTION_END

#endif // HID_DESCRIPTOR_HELPERS_H
